version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven
      - apt-get update -y && apt-get install -y maven

  pre_build:
    commands:
      - echo Starting the pre_build phase...
      - mvn --version

  build:
    commands:
      - echo Building the Spring Boot Application...
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar

cache:
  paths:
    - '/root/.m2/**/*'
